### ISSUE TITLE
Wrong namespace in JsonCommandTraitInterface

### ISSUE THREAD

**Issue by shark555** [averias/phpredis-json#21]
In version 1.2.2 JsonCommandTraitInterface is in namespace Averias\RedisJson\Client which does not fit directory structure and causes error.
I assume it should be in Averias\RedisJson\Command\Traits.

**Comment by averias** [comment]
Hi @shark555,

Thank you so much for finding and informing about this issue, I'll fix it asap

**Comment by averias** [comment]
@shark555 I fixed the issue in version 1.2.3, let me know if you still find that error

**Comment by shark555** [comment]
Thanks for fast reaction. Everything works now.
